/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-28 17:56:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import hotel_Application.FoodBean;

public final class View_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("hotel_Application.FoodBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(" #main {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        max-width: 600px;\r\n");
      out.write("        margin: 100px auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table, th, td {\r\n");
      out.write("	border: 3px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url(\"Stater.jpg\");\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write(" #sub {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        max-width: 300px; /* Set a specific maximum width for the second table */\r\n");
      out.write("        margin-top: 100px;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        margin-right: 200px;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	FoodBean fb = (FoodBean) session.getAttribute("fbean");
	
      out.write("\r\n");
      out.write("	<div id=\"main\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Items</td>\r\n");
      out.write("					<td>Quantity</td>\r\n");
      out.write("					<td>Price</td>\r\n");
      out.write("					<td>TotalPrice</td>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		     </thead>\r\n");
      out.write("		   \r\n");
      out.write("					");

					Double bill=0.0;
					  try{
					if (fb.getLollypop() != null) {
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><strong>");
      out.print(fb.getLollypop());
      out.write("</strong></td>\r\n");
      out.write("					<td>");
      out.print(fb.getLollypopQty());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getLollypopPrice());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getLollypopQty()*fb.getLollypopPrice() );
      out.write("</td>\r\n");
      out.write("					");
 bill=bill+fb.getLollypopQty()*fb.getLollypopPrice(); 
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
		     }catch(Exception e)
		     {
		    	 e.printStackTrace();
		     }
				
      out.write("\r\n");
      out.write("				");

				try{
				if (fb.getCrispyChicken() != null) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><strong>");
      out.print(fb.getCrispyChicken());
      out.write("</strong></td>\r\n");
      out.write("					<td>");
      out.print(fb.getCrispyChickenQty());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getCrispyChickenPrice());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getCrispyChickenQty()*fb.getCrispyChickenPrice() );
      out.write("</td>\r\n");
      out.write("					");
 bill=bill+fb.getCrispyChickenQty()*fb.getCrispyChickenPrice(); 
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				}catch(Exception e)
				{
					e.printStackTrace();
				}
				
      out.write("\r\n");
      out.write("				");

				try{
				if (fb.getButterMasala() != null) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><strong>");
      out.print(fb.getButterMasala());
      out.write("</strong></td>\r\n");
      out.write("					<td>");
      out.print(fb.getButterMasalaQty());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getButterMasalaPrice());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getButterMasalaQty()*fb.getButterMasalaPrice() );
      out.write("</td>\r\n");
      out.write("					");
 bill=bill+fb.getButterMasalaQty()*fb.getButterMasalaPrice() ; 
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				}catch(Exception e)
				{
					e.printStackTrace();
				}
				
      out.write("\r\n");
      out.write("				");

				try{
				if (fb.getHyderabadi() != null) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><strong>");
      out.print(fb.getHyderabadi());
      out.write("</strong></td>\r\n");
      out.write("					<td>");
      out.print(fb.getHyderabadiQty());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getHyderabadiPrice());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getHyderabadiQty()*fb.getHyderabadiPrice() );
      out.write("</td>\r\n");
      out.write("					");
 bill=bill+fb.getHyderabadiQty()*fb.getHyderabadiPrice(); 
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				}catch(Exception e)
				{
					e.printStackTrace();
				}
				
      out.write("\r\n");
      out.write("				");

				try{
				if (fb.getIceCream() != null) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><strong>");
      out.print(fb.getIceCream());
      out.write("</strong></td>\r\n");
      out.write("					<td>");
      out.print(fb.getIceCreamQty());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getIceCreamPrice());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getIceCreamQty()*fb.getIceCreamPrice() );
      out.write("</td>\r\n");
      out.write("					");
 bill=bill+ fb.getIceCreamQty()*fb.getIceCreamPrice();
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				}catch(Exception e)
				{
					e.printStackTrace();
					out.println(fb);
				}
				
      out.write("\r\n");
      out.write("				");

				try{
				if (fb.getGulabJamun() != null) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><strong>");
      out.print(fb.getGulabJamun());
      out.write("</strong></td>\r\n");
      out.write("					<td>");
      out.print(fb.getGulabJamunQty());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getGulabJamunPrice());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(fb.getGulabJamunQty()*fb.getGulabJamunPrice() );
      out.write("</td>\r\n");
      out.write("					");
 bill=bill+fb.getGulabJamunQty()*fb.getGulabJamunPrice(); 
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				}catch(Exception e)
				{
					e.printStackTrace();
					out.println(fb);
				}
				
      out.write("\r\n");
      out.write("			");
 session.setAttribute("Bill", bill); 
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("		<div id=\"sub\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Edit</td>\r\n");
      out.write("					<td><input type=\"button\" value=\"Click\"\r\n");
      out.write("						style=\"font-size: 20px; padding: 10px 20px;\"\r\n");
      out.write("						onclick=\"window.location.href='Food.html';\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				\r\n");
      out.write("					<td>Print Bill</td>\r\n");
      out.write("					<td><input type=\"button\" value=\"Click\"\r\n");
      out.write("						style=\"font-size: 20px; padding: 10px 20px;\"onclick=\"window.location.href='FoodBill.jsp';\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Hotel Rooms</td>\r\n");
      out.write("					<td><input type=\"button\" value=\"Click\" style=\"font-size: 20px; padding: 10px 20px;\" onclick=\"window.location.href='HotelRoom.html';\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
