/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-28 17:58:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import hotel_Application.FoodBean;
import java.lang.*;

public final class ViewTotal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("hotel_Application.FoodBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <title>Bill Summary</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-image: url(\"Payment.jpg\");\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            min-height: 80vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        fieldset {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        table tr {\r\n");
      out.write("            border-bottom: 1px solid #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        table tr:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("        .separator {\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            background-color: #ccc;\r\n");
      out.write("        }\r\n");
      out.write("         button {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background-color: #007BFF;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("         input[type=\"text\"] {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        .button-container {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button-container button {\r\n");
      out.write("            margin: 5px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        FoodBean fb = (FoodBean) session.getAttribute("fbean");
        try {
            Double hotBill = (Double) session.getAttribute("room");
            Double bill = (Double) session.getAttribute("Bill");
            Double totBill = 0.0;
            if (bill != null) {
    
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend style=\"font-size: 40px;\">Bill List</legend>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td style=\"font-size: 24px;\">Food Bill:</td>\r\n");
      out.write("                    <td>");
      out.print( bill );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                    }
                    if (hotBill != null) {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td style=\"font-size: 24px;\">Hotel Bill:</td>\r\n");
      out.write("                    <td>");
      out.print( hotBill );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"separator\">\r\n");
      out.write("                    <td colspan=\"2\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                    }
                    if (bill == null) {
                        totBill = hotBill;
                    }
                    if (hotBill == null) {
                        totBill = bill;
                    }
                    if (bill != null && hotBill != null) {
                        totBill = bill + hotBill;
                    }
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td style=\"font-size: 24px;\">Total Bill:</td>\r\n");
      out.write("                    <td>");
      out.print( totBill );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
}catch(Exception e)
        {}
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"button-container\">\r\n");
      out.write("        <button>\r\n");
      out.write("            <a href=\"Food.html\" style=\"text-decoration: none; color: #fff; padding: 10px;\">Food Want</a>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button>\r\n");
      out.write("            <a href=\"Print.jsp\" style=\"text-decoration: none; color: #fff; padding: 10px;\">Pay</a>\r\n");
      out.write("        </button> \r\n");
      out.write("    </div>      \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
